#!/usr/bin/env bash
#bash script transfer file from client to serve and receive 4 parameters
#+ the path to file tansferred
#+ the ip addres
#+ he username that scp connects with.
#+ the path to te ssh private key

if  [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
