#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo " listen load_balancer
       bind *:80
       mode http
       balnce roundrobin
       option httpclose
       option forwardfor
       server 493721-web-01 54.145.238.253:80 check
       server 493721-web-02 100.26.233.178:80 check
       " > /etc/haproxy/haproxy.cfg
service haproxy start 
