#!/usr/bin/env bash
# Displays "Best School" 10 times using while loop at line 9 display hi on new line.

i=0

while((i<10))
do
  echo "Best School"
  if((i==8))
  then	  
    echo "Hi"
  fi
  ((i++))
done


